### ISSUE TITLE
Silverlight has issues posting errors and getting project settings.

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.Net#1]
I noticed two issues with the latest client when targeting Silverlight. The first issue is a security exception is thrown when posting an error but doesn't happen when debugging (only in release mode). I was able to track down the following stack trace:

	System.Security.SecurityException occurred
	  Message=Security error.
	  StackTrace:
			  at System.Net.Browser.ClientHttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
			  at System.Func`2.Invoke(T arg)
			  at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise)
	  InnerException: 

Next, noticed that there was an issue trying to `GetSettings` in the `DefaultSubmissionClient`. The server returns an OK result with the settings but the client errors out.

	System.Net.WebException occurred
	  Message=The remote server returned an error: NotFound.
	  StackTrace:
		   at System.Net.Browser.ClientHttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
	  InnerException:

**Comment by niemyjski** [comment]
I believe this issue is a result of not having the following configuration: http://stackoverflow.com/questions/8300407/silverlight-httpwebrequest-securityexception

**Comment by niemyjski** [comment]
I'm closing this as we support Silverlight and any issues you may be seeing are addressed in this issue.
