### ISSUE TITLE
Look into issue with App Insights and exceptionless being installed side by side

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.Net#136]
```
Exception information:


    Exception type: ConfigurationErrorsException


    Exception message: Couldn't find type for class Microsoft.ApplicationInsights.TraceListener.ApplicationInsightsTraceListener, Microsoft.ApplicationInsights.TraceListener.

   at System.Diagnostics.TraceUtils.GetRuntimeObject(String className, Type baseType, String initializeData)

   at System.Diagnostics.TypedElement.BaseGetRuntimeObject()

   at System.Diagnostics.ListenerElement.GetRuntimeObject()

   at System.Diagnostics.ListenerElementsCollection.GetRuntimeObject()

   at System.Diagnostics.TraceInternal.get_Listeners()

   at System.Diagnostics.Trace.get_Listeners()

   at Exceptionless.ExceptionlessConfigurationExtensions.UseTraceLogEntriesPlugin(ExceptionlessConfiguration config, Nullable`1 defaultMaxEntriesToInclude)

   at Exceptionless.ExceptionlessClientExtensions.Startup(ExceptionlessClient client, String apiKey)

   at Exceptionless.Mvc.ExceptionlessModule.Init(HttpApplication app)

   at System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers)

   at System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context)

   at System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context)

   at System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext)
```

**Comment by vonlar** [comment]
I doubt this will be reproducible since it was during a NuGet package upgrade of the App Insight packages.  What eventually fixed the issue was right clicking on the project and reconfiguring App Insights since the configuration process has been completely changed.  Note that I attempted to remove App Insights before reconfiguring it.

**Comment by niemyjski** [comment]
We still shouldn't blow up :)

**Comment by vonlar** [comment]
Probably not, but it's likely an App Insights issue that you'll have to help your users through support rather than fixing through code.  But good luck on trying to track down the actual problem and fix!
