### ISSUE TITLE
Blazor WebAssembly Support

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.Net#286]
There are several issues when working with Blazor WebAssembly projects that need to be worked out.

## Async Issues with GetAwaiter().GetResult()

https://github.com/exceptionless/Exceptionless.Net/blob/main/src/Exceptionless/Submission/DefaultSubmissionClient.cs#L43

```
at System.Threading.Monitor.ObjWait(Int32 millisecondsTimeout, Object obj)
at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout)  
at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) 
at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)  
at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at Exceptionless.Submission.DefaultSubmissionClient.PostEvents(IEnumerable`1 events, ExceptionlessConfiguration config, IJsonSerializer serializer)
 in D:\\Code\\Exceptionless.Net\\src\\Exceptionless\\Submission\\DefaultSubmissionClient.cs:line 43
```

## HttpClientHandler UseDefaultCredentials Issue 

We need to check the dotnet runtime issues for existing issues or report a new one as this is where the Blazor team handles these kinds of issues.

https://github.com/exceptionless/Exceptionless.Net/blob/main/src/Exceptionless/Submission/DefaultSubmissionClient.cs#L138

```
System.PlatformNotSupportedException exception 

at System.Net.Http.BrowserHttpHandler.set_Credentials(ICredentials value)
at System.Net.Http.HttpClientHandler.set_UseDefaultCredentials(Boolean value)
at Exceptionless.Submission.DefaultSubmissionClient.CreateHttpClient(ExceptionlessConfiguration config) in D:\\Code\\Exceptionless.Net\\src\\Exceptionless\\Submission\\DefaultSubmissionClient.cs:line 138
at Exceptionless.Submission.DefaultSubmissionClient.<>c__DisplayClass1_0.<.ctor>b__0() in D:\\Code\\Exceptionless.Net\\src\\Exceptionless\\Sub…tpClient, System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].CreateValue()
System.Lazy`1[[System.Net.Http.HttpClient, System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].get_Value()
at Exceptionless.Submission.DefaultSubmissionClient.PostEvents(IEnumerable`1 events, ExceptionlessConfiguration config, IJsonSerializer serializer) in D:\\Code\\Exceptionless.Net\\src\\Exceptionless\\Submission\\DefaultSubmissionClient.cs:line 42
```

**Comment by niemyjski** [comment]
Blazor is now supported with the 5.0 release.
