### ISSUE TITLE
Exception occurred while creating an instance of the ExceptionlessClient

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.Net#52]
```csharp
(SocketException) An operation was attempted on something that is not a socket

at System.Net.SafeCloseSocketAndEvent.CreateWSASocketWithEvent(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType, Boolean autoReset, Boolean signaled)
   at System.Net.NetworkInformation.NetworkChange.AddressChangeListener.StartHelper(NetworkAddressChangedEventHandler caller, Boolean captureContext, StartIPOptions startIPOptions)
   at System.Net.NetworkInformation.NetworkChange.AvailabilityChangeListener.Start(NetworkAvailabilityChangedEventHandler caller)
   at System.Net.NetworkInformation.NetworkChange.add_NetworkAvailabilityChanged(NetworkAvailabilityChangedEventHandler value)
   at Exceptionless.ExceptionlessClient..ctor(IQueueStore store, IExceptionlessLog log)
   at Exceptionless.ExceptionlessClient.<.cctor>b__11()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Exceptionless.ExceptionlessClient.get_Current()
   at Exceptionless.ErrorExtensions.ToExceptionless(Exception exception, Boolean addDefaultInformation, IDictionary`2 pluginContextData, ExceptionlessClient client)
   at Exceptionless.ErrorExtensions.ToExceptionless(Exception exception)
   at Example.ErrorHandling.ErrorsLogProvider.WriteLogEntry(ErrorLevel level, Object message, Exception exception) in c:\Users\USER\Source\Repos\Example\Source\Example\ErrorHandling\ErrorsLogProvider.cs:line 166
   at Example.ErrorHandling.ErrorsLogProvider.Error(String message, Exception exception) in c:\Users\USER\Source\Repos\Example\Source\Example\ErrorHandling\ErrorsLogProvider.cs:line 55
   at Example.External.ExampleMethods.FetchExampleRating() in c:\Users\USER\Source\Repos\Example\Source\Example\External\ExampleMethods.cs:line 35
   at Example.Presentation.SiteCache.BragAboutExampleReviews() in c:\Users\USER\Source\Repos\Example\Source\Example\Presentation\SiteCache.cs:line 70
   at Example.ViewModels.SupplierRegisterViewModel..ctor() in c:\Users\USER\Source\Repos\Example\Source\Example.Web\ViewModels\SupplierRegisterViewModel.cs:line 33
   at Example.Controllers.SuppliersController.Register(String version, Boolean campaign) in c:\Users\USER\Source\Repos\Example\Source\Example.Web\Controllers\SuppliersController.cs:line 59
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.ActionInvocation.InvokeSynchronousActionMethod()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
```

**Comment by niemyjski** [comment]
This has been fixed in 3.x
